# Generated by Django 5.0.1 on 2024-01-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0006_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='chamaapp.profile'),
        ),
    ]
