# Generated by Django 5.0.1 on 2024-01-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0009_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='MeetingTitle',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='meetingDate',
        ),
    ]
