# Generated by Django 5.0.1 on 2024-01-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0010_rename_title_meeting_meetingtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='MeetingTitle',
            field=models.CharField(max_length=50),
        ),
    ]
