# Generated by Django 5.0.1 on 2024-01-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0013_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='meetingDescription',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='MeetingTitle',
            new_name='meetingTitle',
        ),
    ]
