# Generated by Django 5.0.1 on 2024-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0015_alter_meeting_meetingdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
