# Generated by Django 5.0.1 on 2024-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0017_alter_meeting_meetingtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingTitle',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
