# Generated by Django 5.0.1 on 2024-01-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamaapp', '0022_alter_meeting_meetingdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
